version: 0.0
os: linux

# Dev branch settings
branches:
  dev:
    files:
      - source: /
        destination: /var/www/html/one
        overwrite: true
    fileExistsBehavior: OVERWRITE
    
    hooks:
      BeforeInstall:
        - location: scripts/dev_before_install.sh
          timeout: 300
          runas: ubuntu
      AfterInstall:
        - location: scripts/dev_after_install.sh
          timeout: 300
          runas: ubuntu
      ApplicationStart:
        - location: scripts/dev_application_start.sh
          timeout: 300
          runas: ubuntu
    

# Prod branch settings
  prod:
    files:
      - source: /
        destination: /var/www/html/second
        overwrite: true
    fileExistsBehavior: OVERWRITE

    hooks:
      BeforeInstall:
        - location: scripts/prod_before_install.sh
          timeout: 300
          runas: ubuntu
      AfterInstall:
        - location: scripts/prod_after_install.sh
          timeout: 300
          runas: ubuntu
      ApplicationStart:
        - location: scripts/prod_application_start.sh
          timeout: 300
          runas: ubuntu
    
