version: 0.0
os: linux

files: &common_files
  - source: /
    destination: /var/www/html/
    overwrite: true
    fileExistsBehavior: OVERWRITE

branches:
  dev:
    - <<: *common_files
      destination: /var/www/html/one
  prod:
    - <<: *common_files
      destination: /var/www/html/second