version: 0.0
os: linux

permissions:
  - object: /var/www/html/one
    owner: ubuntu
    group: webdevs
    mode: '0775'
  - object: /var/www/html/second
    owner: ubuntu
    group: webdevs
    mode: '0775'

# Dev branch settings
branches:
  dev:
    files:
      - source: /
        destination: /var/www/html/one
        overwrite: true
        permissions:
          - object: /var/www/html/one
            pattern: '**/*'
            owner: ubuntu
            group: webdevs
            mode: '0775'
    fileExistsBehavior: OVERWRITE
    
    hooks:
      ApplicationStart:
        - location: scripts/dev_application_start.sh
          timeout: 300
          runas: ubuntu
          when:
            branch: "dev"
    

# Prod branch settings
  prod:
    files:
      - source: /
        destination: /var/www/html/second
        overwrite: true
        permissions:
          - object: /var/www/html/second
            pattern: '**/*'
            owner: ubuntu
            group: webdevs
            mode: '0775'
    fileExistsBehavior: OVERWRITE

    hooks:
      ApplicationStart:
        - location: scripts/prod_application_start.sh
          timeout: 300
          runas: ubuntu
          when:
            branch: "prod"
    
