version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root

files:
  - source: /
    destination: /var/www/html/
    overwrite: true
    fileExistsBehavior: OVERWRITE
