version: 0.0
os: linux

files:
  - source: /
    destination: /home/my-temp-dir
    overwrite: true
    fileExistsBehavior: OVERWRITE
    exclude:
      - \..*
permissions:
  - object: /home/my-temp-dir
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/set_destination.sh
      runas: root
  AfterInstall:
    - location: scripts/integrations-deploy-post.sh
      runas: root