version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/one
    overwrite: true
    fileExistsBehavior: OVERWRITE

hooks:
      ApplicationStart:
        - location: scripts/prod_application_start.sh
          timeout: 300
          runas: ubuntu
          when:
            branch: "prod"