version: 0.0
os: linux

environment:
  DESTINATION_dev: /var/www/html/one
  DESTINATION_prod: /var/www/html/second
  
files:
  - source: /
    destination: ${{ env["DESTINATION_${{ github.ref }}"] }}
    overwrite: true
    fileExistsBehavior: OVERWRITE

hooks:
      ApplicationStart:
        - location: scripts/prod_application_start.sh
          timeout: 300
          runas: ubuntu
          when:
            branch: "prod"