version: 0.0
os: ubutnu

# Dev branch settings
branches:
  dev:
    files:
      - source: /
        destination: /var/www/html/one
        overwrite: true
    fileExistsBehavior: OVERWRITE
    
    hooks:
      ApplicationStart:
        - location: scripts/dev_application_start.sh
          timeout: 300
          runas: ubuntu
          when:
            branch: "dev"
    

# Prod branch settings
  prod:
    files:
      - source: /
        destination: /var/www/html/second
        overwrite: true
    fileExistsBehavior: OVERWRITE

    hooks:
      ApplicationStart:
        - location: scripts/prod_application_start.sh
          timeout: 300
          runas: ubuntu
          when:
            branch: "prod"
    
