# # trigger:
# # # - main

# pool:
#   vmImage: ubuntu-latest

# steps:

# - script: |
# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '/home/vsts/work/1/s'
#     Contents: '**'
#     TargetFolder: '/home/vsts/work/1/a'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'